useCase0:
  API_KEY: "exampleapikey"
  # API key MUST be surrounded by quotation marks. Example: "92475627934FWR5455ERW"
  # Preferably, delete after usage.

useCase1:
  #No need for input

useCase2:
  DESIRED_YEAR: 2023
  DESIRED_QUARTER: 1
  # Quarters are [1,2,3,4] and any other quarter is invalid.

useCase3:
  ORG_ID: "Example_Org"
  CONTRACT_EXPIRY_DATE: "31-05-2023"
  # CONTRACT_EXPIRT_DATE must be of the form DD-MM-YYYY

useCase4:
  #To be implemented
