#Set the Finance Billing Quarterly Dates Here.
#   I have set example quarterly billing dates here, change if RTT billing cycle is different.

#   Only set the DAY and MONTH in DD-MM format.
#   DO NOT PROVIDE THE YEAR.
#   Use values as-is; for example, for January or first day-of-month, it will be 1 and not 01!
dateConfig:
  #Quarter One Data --------------------------
  # ------------------------------------------
  q1StartDay: 1 # 1-31 DAY OF MONTH
  q1StartMonth: 1 # 1-12 JAN TO DEC
  # ----
  q1EndDay: 31
  q1EndMonth: 3
  #Quarter Two Data --------------------------
  # ------------------------------------------
  q2StartDay: 1
  q2StartMonth: 4
  # ----
  q2EndDay: 30
  q2EndMonth: 6
  #Quarter Three Data ------------------------
  # ------------------------------------------
  q3StartDay: 1
  q3StartMonth: 7
  # ----
  q3EndDay: 30
  q3EndMonth: 9
  #Quarter Four Data -------------------------
  # ------------------------------------------
  q4StartDay: 1
  q4StartMonth: 10
  # ----
  q4EndDay: 31
  q4EndMonth: 12